// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjj0QJrEfNaVI2xLmixLFH86eKsqpyV_U',
    appId: '1:254803010706:web:01db75b6204de1b5ac324b',
    messagingSenderId: '254803010706',
    projectId: 'mega-mart-13ac5',
    authDomain: 'mega-mart-13ac5.firebaseapp.com',
    storageBucket: 'mega-mart-13ac5.appspot.com',
    measurementId: 'G-KVNW2WNE9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiOoNqSkyqYRSQPGykJCuUNkyLd9R2zL8',
    appId: '1:254803010706:android:816675471a9165a2ac324b',
    messagingSenderId: '254803010706',
    projectId: 'mega-mart-13ac5',
    storageBucket: 'mega-mart-13ac5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN5Q7h__7iZQTNugMc0qYCtDUbBsko6tU',
    appId: '1:254803010706:ios:70616778a1e8af88ac324b',
    messagingSenderId: '254803010706',
    projectId: 'mega-mart-13ac5',
    storageBucket: 'mega-mart-13ac5.appspot.com',
    iosBundleId: 'com.example.theNewapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN5Q7h__7iZQTNugMc0qYCtDUbBsko6tU',
    appId: '1:254803010706:ios:70616778a1e8af88ac324b',
    messagingSenderId: '254803010706',
    projectId: 'mega-mart-13ac5',
    storageBucket: 'mega-mart-13ac5.appspot.com',
    iosBundleId: 'com.example.theNewapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjj0QJrEfNaVI2xLmixLFH86eKsqpyV_U',
    appId: '1:254803010706:web:29b147b7ea4a86f1ac324b',
    messagingSenderId: '254803010706',
    projectId: 'mega-mart-13ac5',
    authDomain: 'mega-mart-13ac5.firebaseapp.com',
    storageBucket: 'mega-mart-13ac5.appspot.com',
    measurementId: 'G-0Q1SD14D85',
  );

}